### ISSUE TITLE
Module Request: Shure Axient Digital

### ISSUE THREAD

**Issue by larskmann** [bitfocus/companion-module-shure-wireless#1]
**Describe the feature**
As the Shure Axient Digital is able to connect up to eight Transmitters to one Receiver Channel and you can RF Mute / Unmute each of these Transmitters it would be great to have control over that functionality. Its kinda nasty to do it in Shures Native way, as you have to reach out to every Receiver by Hand. But Telnet Control is available and also able to do the Job.
If other features also seem useful (Readout of Battery State, Triggering of different Frequencies??) its also possible.

**Is this platform dependent (windows, mac, ..)?**
No as Axient Digital is the platform delivering the information / Being triggered.

**If documentation is required to implement, do you know where to find it?**
[Axient_Digital_network_string_commands.pdf](https://github.com/bitfocus/companion/files/3356111/Axient_Digital_network_string_commands.pdf)

**Usecases**
HF Engineer, FoH Engineer, Theater, House of Whorship alike. Easy swapping of Sets of Transmitters (Backing Vox / Guitar Sets)

**Comment by hmhead** [comment]
I am using this module for the first time on show site.  It seems the Transmitter OFF feedback option isn't working.  I am using Axient Digital AD4Q and have transmitters on two channels.  If I add the Transmitter Off to that button it automatically colors for Transmitter off even if its on.  The battery indicator seems to be working great.  I did make sure only one transmitter was synced to that particular receiver channel and no change.  Any thoughts?

**Comment by krocheck** [comment]
This module should be operational with AD series now with the latest dev build.  Please open a new issue for any problems.
