### ISSUE TITLE
QLX-D No Feedback

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-shure-wireless#11]
Using QLXD single receivers I have been unable to get any feedback working with both of our units.  I have also tried showing the top bar in Companion per the other issue listed.  This does make the template for the feedbacks appear on the button but with no actual feedback data working.  Latest beta builds.  Connection shows correctly.  Firmware update and model DO appear but all other feedbacks appear as undefined.  Thanks for all you developers do.  Anything I can do to help get this fixed please let me know!

**Comment by obcocav** [comment]
@krocheck .  Any ideas?  Thanks!

**Comment by obcocav** [comment]
As a point of reference I have a companion pi on build 2.2.0 3117 and feedback works there though removing the button top bar still causes a crash and loss of feedback still.

**Comment by jsnyder886** [comment]
I'm having the same trouble with a QLXD receiver.  The connection had been working fine prior to uploading to a new beta. 
 I updated to still another beta hoping maybe it was just a weird glitch and still no feedback or variables working.  Current version I'm working on is 2.2.0 (2.2.0-5508c413-3481).  Thanks in advance for any help anyone might be able to offer!

**Comment by isaiahfranco** [comment]
I'm having issues with connecting to my QLX-D receivers and Axient Digital AD4Q receivers. I don't remember the last time it worked but definitely does not work in the beta builds.

**Comment by isaiahfranco** [comment]
I forked the module and ran it locally and guess what? It worked! I'm not sure what's different between what I'm running locally vs the beta build but it can and should be working!
