### ISSUE TITLE
Level of Effort for MXWAPT

### ISSUE THREAD

**Issue by peppertechie** [bitfocus/companion-module-shure-wireless#15]
We have an MXWAPT8 and I am wondering the level of effort to officially support this device?
I have tried to connect to the MXWANI8 and just get a connection error with no variables populating. 

Documentation is here. 
https://pubs.shure.com/command-strings/MXW/en-US

I have access to a windows and linux machine on the same network for testing.

**Comment by peternewman** [comment]
See https://github.com/bitfocus/companion-module-shure-wireless/pull/18/commits/cfbf93862b5976dc15b1a9239f66c8bb3bd8391e looks like it just needs porting.

**Comment by krocheck** [comment]
`shure-mxw` module is available in 3.1.x stable releases.
