### ISSUE TITLE
Cant generate a trigger from RF levels 

### ISSUE THREAD

**Issue by AlexHasker** [bitfocus/companion-module-shure-wireless#17]
Ive tried making a trigger to change a button color based on RF levels and can only get a response using the EQUALS or NOT EQUALS functions.  No change in button colour using the GREATER THAN or LESS THAN functions .
Ive tried using values "learned"  in the exact format displayed (-98 dBm) , ive also tried numeric with the minus symbol and without the minus symbol, still no change 
Is it possible the "dBm" isnt being filtered by this Shure module  and is causing  problems  with the GREATER THAN and LESS THAN function ?

**Comment by krocheck** [comment]
Which model does this pertain to?

**Comment by AlexHasker** [comment]
Shure ULXD (current firmware from Shure) and current stable PC release of Companion 2.4.2.


Sincerely



Alex Hasker





Lex Audio Visual Pty Ltd

A.B.N. 82 095 213 193

A.C.N.  095 213 193<tel:095%20213%20193>

Factory 3/123 Chesterville Rd,

Highett, Vic 3190

Melbourne, Australia

www.LexAudioVisual.com.au<http://www.lexaudiovisual.com.au/>

Email ***@***.******@***.***>

Phone 03 9532 3006<tel:03%209532%203006>

Mobile 0418 307 485<tel:0418%20307%20485>





Accounts

For all account queries, please contact:

Lex Audio Visual accounts c/o The Outsourced Office

Suite 4, 1414 Toorak Road

Camberwell,  VIC  3124

Email: ***@***.******@***.***>

Phone 03 9889 1957<tel:03%209889%201957>

________________________________

**Comment by krocheck** [comment]
Yeah, so if you look at the code the units are actually being injected into the variables to make them human readable.  This is because the module existed long before expressions could be done on numeric variables.  So I'm not surprised this isn't working for you currently.

But I am working on the v3 upgrade and have disabled unit printouts in the variables ([4ffb2df](https://github.com/bitfocus/companion-module-shure-wireless/pull/18/commits/4ffb2dfd5228d9ecf62383b79a97a8aaf63deaec)).  This hasn't been pushed to the Companion 3 betas, but will in a day or two.  Are you able to test at that time?

**Comment by krocheck** [comment]
Actually, I'll do you one better ... how about we let the user pick, that way I don't break anyone who likes seeing the units.  See picture: 
![image](https://user-images.githubusercontent.com/749812/219960318-515ebb14-891d-4be7-a57f-f3eea6c08a02.png)

**Comment by AlexHasker** [comment]
Hi Keith

Sure , happy to test it out and user selectable units is a good idea, makes the interface easier for users to understand what they are playing with

If you can, let me know when the update has been pushed and Ill have a crack


Sincerely



Alex Hasker





Lex Audio Visual Pty Ltd

A.B.N. 82 095 213 193

A.C.N.  095 213 193<tel:095%20213%20193>

Factory 3/123 Chesterville Rd,

Highett, Vic 3190

Melbourne, Australia

www.LexAudioVisual.com.au<http://www.lexaudiovisual.com.au/>

Email ***@***.******@***.***>

Phone 03 9532 3006<tel:03%209532%203006>

Mobile 0418 307 485<tel:0418%20307%20485>





Accounts

For all account queries, please contact:

Lex Audio Visual accounts c/o The Outsourced Office

Suite 4, 1414 Toorak Road

Camberwell,  VIC  3124

Email: ***@***.******@***.***>

Phone 03 9889 1957<tel:03%209889%201957>

________________________________

**Comment by krocheck** [comment]
Variable format was added in an earlier release
