### ISSUE TITLE
Can't find the module in Companion

### ISSUE THREAD

**Issue by BasTimmer** [bitfocus/companion-module-shure-wireless#2]
hey sorry probably not the good place to ask this but in what version can i find this module,
i have already checked 1.3.0, 1.4.0 and 2.0.0 or is it still in development ??

greetings,
Bas

**Comment by josephdadams** [comment]
Hey @BasTimmer, it’s still in development, but you’re gonna love it when it is released. :)

**Comment by BasTimmer** [comment]
Can't wait for it

**Comment by McHauge** [comment]
@BasTimmer if you want to test it, then it's included in most of my test builds at:
[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)
