### ISSUE TITLE
Connection goes to error state randomly

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-shure-wireless#21]
My connection to two Shure QLXD units seemingly randomly goes into error state.  I have to power cycle the receivers themselves then cycle the connection to fix it.  Has been happening for a while but hoped 3.0 would solve it.

**Comment by krocheck** [comment]
TBH, I used to see this in my receivers that were monitored using Crestron systems on 24/7 basis.  This was ULX-D's and 7+ years ago at this point.

For that we changed the meter rate to a long interval, such as 1 minute, or possibly disabled metering altogether.  From what I recall most of these issues went away then.

I don't think there's anything we can change in the Companion implementation to mitigate this.
