### ISSUE TITLE
Set NAME by variable

### ISSUE THREAD

**Issue by TigerAudio** [bitfocus/companion-module-shure-wireless#26]
I am using the Sheets module for companion to sync cells from google sheets into companion.  I would like to have the RF channel names populate in the NAME field under the button action SET NAME.  Currently I can only type something there. WHen I paste the variable for that Sheets cell, it doesn’t like it and it tries to use the variable as the name.

**Comment by TigerAudio** [comment]
Yes, Just tell me what to do!  I have 12 channels of ULXD Q and 1 channel of ULXD.

**Comment by istnv** [comment]
@TigerAudio It has been merged into the beta releases. Update your companion.
