### ISSUE TITLE
Meters are very slow compared to WWB

### ISSUE THREAD

**Issue by TigerAudio** [bitfocus/companion-module-shure-wireless#27]
If possible, if the refresh rate of the meters could be 20ms instead of 500ms, that would be very useful for those of us using this to get digital (dante) levels where they need to be to hit a digital mixer with no other gain controls available.

**Comment by istnv** [comment]
Have you tried changing the interval on the 'Edit connection' tab?
![image](https://github.com/bitfocus/companion-module-shure-wireless/assets/51003420/d3a39fc7-5ba0-488b-8547-b60a90510aa0)

**Comment by TigerAudio** [comment]
Yes, 500ms, (1/2 second) is the lowest setting.  It needs to be about 10ms.  Thanks

**Comment by istnv** [comment]
Lower than 50 and the module can starve its own buttons from running.

**Comment by TigerAudio** [comment]
The Shure software that monitors the units doesn’t have that issue however.  You can run WWB and easily use Q Lab, etc on the same machine. That leads me to think there is something in the programming of the meters that makes it CPU heavy.  In any case, 500 was the lowest it would go last I checked.  I think it would depend on the computer as to whether this is an issue or not.

**Comment by istnv** [comment]
@TigerAudio Also in the latest betas. The input has adjusted to allow 50ms with a warning about potential slowing.
