### ISSUE TITLE
Frequency Change not work with 3.2

### ISSUE THREAD

**Issue by Kusi44** [bitfocus/companion-module-shure-wireless#32]
I try to change Frequency of a Shure AD4Q receiver. With version 3.1 it all works smooth, with 3.2 it's not reacting. Other actions like decrease audio gein of flash lights work.
Anybody?

**Comment by krocheck** [comment]
@istnv

**Comment by istnv** [comment]
I no longer have access to the receiver I was testing with.
That typo has been there for a while. 
Should work with next beta release.
