### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by HDHIMT** [bitfocus/companion-module-shure-wireless#39]
Hello,
when adding the module to my Companion and setting up the ip of my Shure SLX-D4, Companion prompts me with "ERROR
connect ECONNREFUSED 10.123.123.100:2202". I've choosen the right model in Companion. I get a response of my mic when I'm pinging it. Even with Shure Wireless Workbench I can connect to the mic. So the IP is correct. Do you have any idea why I cannot add it to Companion?

![companion-shure](https://github.com/bitfocus/companion-module-shure-wireless/assets/172396337/bd4f8b06-8be7-4600-99f2-2ba81dec7547)

**Comment by kuuminsh** [comment]
[SLX-D - Wireless System - Product documentation](https://pubs.shure.com/view/guide/SLXD/en-US.pdf)

SLX-D blocks command strings by default. You can block or allow third-party controls in the Advanced Settings > Controller Access menu
