### ISSUE TITLE
Set audio gain of channel is treating integers as text

### ISSUE THREAD

**Issue by crackley** [bitfocus/companion-module-shure-wireless#42]
When trying to set the gain of a channel, I was getting unexpected results. Most values that I sent were ignored but some resulted in changes that made no sense. After doing some packet sniffing I found that the module is handling my gain value as text and  concatenating it with the number 18 instead of adding 18 to it. So if I try and set the gain to 5, for example, the command that is sent is < SET 1 AUDIO_GAIN 518 > instead of < SET 1 AUDIO_GAIN 23 >

**Comment by krocheck** [comment]
@istnv this appears to be a consequence of the change to `textinput` without addressing the execution (https://github.com/bitfocus/companion-module-shure-wireless/blob/0c41edebf2d60ac7d2bc59560841b2f47b42e0de/src/actions.js#L40).

**Comment by istnv** [comment]
Should be fixed in the next beta release.
Re-open if this is still an issue as I no longer have access to any hardware for testing.
