### ISSUE TITLE
Axient Lock on ADX1

### ISSUE THREAD

**Issue by FirefoxEurl** [bitfocus/companion-module-shure-wireless#47]
Hello Guys, 

I'm discovering this fantastic APP .
I'm a RF tech on many Musicals, and i'm trying to find a way to lock Over the air on my ADX1 . 
We can see if the lock in on or off on the APP, but there is no action to trigger the lock ON or OFF. 

I'm in need of this fonction in order to prepare the ADX1 early in the belts before the show begins. 
WIth the ADX as soon as you place the batterie if the ADX is power lock, the ADX power on either if it's ON or OFF. 

Cheers Guys

**Comment by krocheck** [comment]
Per Shure documentation, the API we have access to shows TX_LOCK as a read-only property.  You'd have to ask Shure to implement this in their API first.
![image](https://github.com/user-attachments/assets/4ba0cf7d-9ad6-44c3-9f6d-f11c7894235e)
Feel free to re-open based on what Shure tells you.
