### ISSUE TITLE
Reference error: id is not defined

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion-module-shure-wireless#5]
I've cloned your repo and put it in lib/module folder (after renamed it shure-wireless).
I can create an ad4q instance in companion but after applying this creation companion crashed with javascript popups with message(first line):
Reference error: id is not defined

**Comment by McHauge** [comment]
Just did the same myself to test it, and got this, but keep in mind I don't have the hardware. but I ended up with this:

no crash:
set slot rf output
flash light on reciver channel
flash light on reciver
decrease audio gain of channel
increase audio gain of channel
set audio gain of channel
mute or unmyte channel

crash:
set channel name, error: cannot read propertt 'substr' of undefined at instance.action

**Comment by krocheck** [comment]
Question @McHauge did you have a string entered into the 'Name' field for that action?  Not sure I see how that error is popping up yet.

Keith

**Comment by McHauge** [comment]
@krocheck did not even get the option, when I selected the action the button broke and I had to delete it to use it again, looked like a miss configuration of the action

**Comment by krocheck** [comment]
Ahhh ... you should have lead with that ;)

For that I have an idea of what's wrong!

**Comment by McHauge** [comment]
yea, I probably should have, but we got there anyway ;)

**Comment by McHauge** [comment]
@krocheck I believe I just found the error, there is a custom test build named "Companion-2.0-Shure-Wireless_QuickFix.zip" with the fix at the link below:
[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by McHauge** [comment]
Since the fix has now been included in the module, I'm gonna close this, if another or the same problem comes again feel free to open it again.
