### ISSUE TITLE
shure module integration

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion-module-shure-wireless#6]
Hello,
Is there a roadmap to integrate your module in next companion release(2.0)?
I want to test it on windows release (because of crashes on rpi release).
Regards

**Comment by McHauge** [comment]
Hey, not sure about the roadmap, but for testing I do have it included in my test build's for windows at the link below, feel free to use them for testing of the module
https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g

**Comment by dewiweb** [comment]
Thanks a lot,
I'd test it and I've got the same bug  as rpi version:
![Sans titre](https://user-images.githubusercontent.com/3625655/66987509-34ff1f00-f0c1-11e9-9989-25199fae8bea.png)
(url)

**Comment by McHauge** [comment]
When does the error show up?

**Comment by dewiweb** [comment]
After "apply changes" during instance creation

**Comment by McHauge** [comment]
hmm, does it also happen if you chose another device?

**Comment by dewiweb** [comment]
Yes, I've got two AD4Q quad receivers and the result is the same for it.

**Comment by McHauge** [comment]
oh sory, ment in the module

**Comment by dewiweb** [comment]
Other instances work fine!
It only happen with shure module!

**Comment by McHauge** [comment]
I think I found the error, will compile a new build, in a minute

**Comment by McHauge** [comment]
There should now be a file called Companion-2.0-Shure-Wireless_QuickFix.zip with the fix that might work

**Comment by dewiweb** [comment]
Well done,
It works fine now.
Kind regards

**Comment by McHauge** [comment]
Glad to help, I will update the module with the fix, guess we can close this issue and the other one for now then.

**Comment by McHauge** [comment]
Since the fix has now been included in the module, I'm gonna close this, if another or the same problem comes again feel free to open it again.

**Comment by jeffmpelletier** [comment]
Hey all, forgive my newb question... How do I load the module into
Companion?

**Comment by McHauge** [comment]
@jeffmpelletier if you download the V2.0 builds, then it should be there ready for use. for use in V1.4 then you would need someone or yourself to compile it for you, it's not just "a drag and drop" thing.
